### ISSUE TITLE
undervolt --read error

### ISSUE THREAD

**Issue by jonneymendoza** [georgewhewell/undervolt#110]
AM getting this error after executing undervold --read

```modprobe: ERROR: could not insert 'msr': Operation not permitted
Traceback (most recent call last):
  File "/home/me/.local/bin/undervolt", line 8, in <module>
    sys.exit(main())
  File "/home/me/.local/lib/python3.8/site-packages/undervolt.py", line 254, in main
    subprocess.check_call(['modprobe', 'msr'])
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['modprobe', 'msr']' returned non-zero exit status 1.
```

**Comment by Altu101** [comment]
I have same issue on Kubuntu 20.04 (i7 7700HQ). No secure boot. 
Edit: I was able to make it run. I changed form legacy mode to uefi in bios and then reinstall the os.
