### ISSUE TITLE
Error on read existing values and to try set a new value of undervolt.

### ISSUE THREAD

**Issue by italodea** [georgewhewell/undervolt#111]
The only change that really is set is the target temperature.

Ubuntu 20.04 (default gnome)
undervolt 0.3.0
python 3.8.2
pip 20.0.2

Samsung NP-300V4A
i5-2430M
intel HD-Graphics 3000
6GB DDR3

italo@np300:~$ sudo undervolt --core 0
Traceback (most recent call last):
  File "/usr/local/bin/undervolt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/undervolt.py", line 401, in main
    set_offset(plane, offset, msr)
  File "/usr/local/lib/python3.8/dist-packages/undervolt.py", line 218, in set_offset
    write_msr(write_value, msr.addr_voltage_offsets)
  File "/usr/local/lib/python3.8/dist-packages/undervolt.py", line 79, in write_msr
    os.write(f, pack('Q', val))
OSError: [Errno 5] Input/output error

italo@np300:~$ sudo undervolt -r
temperature target: **-5 (95C)**
Traceback (most recent call last):
  File "/usr/local/bin/undervolt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/undervolt.py", line 445, in main
    voltage = read_offset(plane, msr)
  File "/usr/local/lib/python3.8/dist-packages/undervolt.py", line 204, in read_offset
    write_msr(value_to_write, msr.addr_voltage_offsets)
  File "/usr/local/lib/python3.8/dist-packages/undervolt.py", line 79, in write_msr
    os.write(f, pack('Q', val))
OSError: [Errno 5] Input/output error

italo@np300:~$ **sudo undervolt -t 90**

italo@np300:~$ sudo undervolt -r
temperature target: **-10 (90C)**
Traceback (most recent call last):
  File "/usr/local/bin/undervolt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/undervolt.py", line 445, in main
    voltage = read_offset(plane, msr)
  File "/usr/local/lib/python3.8/dist-packages/undervolt.py", line 204, in read_offset
    write_msr(value_to_write, msr.addr_voltage_offsets)
  File "/usr/local/lib/python3.8/dist-packages/undervolt.py", line 79, in write_msr
    os.write(f, pack('Q', val))
OSError: [Errno 5] Input/output error

**Comment by DyJohnnY** [comment]
I have a Intel Pentium Silver J5005 and get his error mesage when trying to read data:

 undervolt -r
temperature target: -0 (100C)
Traceback (most recent call last):
  File "/usr/local/bin/undervolt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/undervolt.py", line 445, in main
    voltage = read_offset(plane, msr)
  File "/usr/local/lib/python3.8/dist-packages/undervolt.py", line 204, in read_offset
    write_msr(value_to_write, msr.addr_voltage_offsets)
  File "/usr/local/lib/python3.8/dist-packages/undervolt.py", line 79, in write_msr
    os.write(f, pack('Q', val))
OSError: [Errno 5] Input/output error
