### ISSUE TITLE
ERROR: could not insert 'msr': Operation not permitted

### ISSUE THREAD

**Issue by QazCetelic** [georgewhewell/undervolt#118]
When running `undervolt --read`
```
modprobe: ERROR: could not insert 'msr': Operation not permitted
Traceback (most recent call last):
  File "/home/qaz/.local/bin/undervolt", line 11, in <module>
    sys.exit(main())
  File "/home/qaz/.local/lib/python2.7/site-packages/undervolt.py", line 386, in main
    subprocess.check_call(['modprobe', 'msr'])
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['modprobe', 'msr']' returned non-zero exit status 1
```

Using Intel i7-8750H (12)

I also tried `sudo undervolt --read`, which gave me the following error message:
`sudo: undervolt: command not found`

**Comment by QazCetelic** [comment]
Closed because it's a duplicate of #46
