### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/dev/cpu/0/msr'

### ISSUE THREAD

**Issue by kachapman** [georgewhewell/undervolt#161]
When trying to use the program, I get this output:

> USER:~$ undervolt -r
Traceback (most recent call last):
  File "/home/kenchapman/.local/bin/undervolt", line 8, in <module>
    sys.exit(main())
  File "/home/kenchapman/.local/lib/python3.9/site-packages/undervolt.py", line 439, in main
    temp = read_temperature(msr)
  File "/home/kenchapman/.local/lib/python3.9/site-packages/undervolt.py", line 191, in read_temperature
    return (read_msr(msr.addr_temp) & (127 << 24)) >> 24
  File "/home/kenchapman/.local/lib/python3.9/site-packages/undervolt.py", line 88, in read_msr
    f = os.open(n, os.O_RDONLY)
PermissionError: [Errno 13] Permission denied: '/dev/cpu/0/msr'

**Comment by georgewhewell** [comment]
use `sudo`

**Comment by kachapman** [comment]
I forgot to mention that Sudo doesn't fix the issue.

-------- Original Message --------

**Comment by kachapman** [comment]
```
ken-sb2:~$ undervolt -r
You need to have root privileges to run this script with these options.
Rerun with 'sudo'.
ken-sb2:~$ sudo undervolt -r
sudo: undervolt: command not found
```

**Comment by kachapman** [comment]
Looks like the issue was secure boot all along. Is there no way to enable this with secure boot enabled?
