### ISSUE TITLE
Cannot use 'undervolt' after upgrading to Fedora 35

### ISSUE THREAD

**Issue by noitisoprepus** [georgewhewell/undervolt#164]
**Device details:**

> OS: Fedora Linux 35 (Workstation Edition) x86_64 
> Host: ThinkPad X270 
> Kernel: 5.14.16-301.fc35.x86_64 
> DE: GNOME 41.1 
> CPU: Intel i5-7300U (4) @ 3.500GHz 
> GPU: Intel HD Graphics 620 
> Memory: 7820MiB

**$ sudo undervolt --read**

> Traceback (most recent call last):
>   File "/usr/local/bin/undervolt", line 33, in <module>
>     sys.exit(load_entry_point('undervolt==0.3.0', 'console_scripts', 'undervolt')())
>   File "/usr/local/bin/undervolt", line 22, in importlib_load_entry_point
>     for entry_point in distribution(dist_name).entry_points
>   File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 919, in distribution
>     return Distribution.from_name(distribution_name)
>   File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 518, in from_name
>     raise PackageNotFoundError(name)
> importlib.metadata.PackageNotFoundError: No package metadata was found for undervolt

**Comment by noitisoprepus** [comment]
It turns out, pip also got removed after the Fedora 35 upgrade. After reinstalling undervolt through pip, everything works fine again.
