### ISSUE TITLE
No package metadata was found for undervolt

### ISSUE THREAD

**Issue by AustinDNelson** [georgewhewell/undervolt#172]
When I type this command
`sudo undervolt -r`

I get this error

> `Traceback (most recent call last):
> File "/home/USER/.local/bin/undervolt", line 33, in <module>
> sys.exit(load_entry_point('undervolt==0.3.0', 'console_scripts', 'undervolt')())
> File "/home/USER/.local/bin/undervolt", line 22, in importlib_load_entry_point
> for entry_point in distribution(dist_name).entry_points
> File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
> return Distribution.from_name(distribution_name)
> File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
> raise PackageNotFoundError(name)
> importlib.metadata.PackageNotFoundError: No package metadata was found for undervolt`

I'm able to do what was suggested at the end of [this](https://github.com/georgewhewell/undervolt/issues/167) issue, but that's pretty inconvenient. I seem to be getting that error with every undervolt command I try. 

I'm on an arch-based distro

Please let me know if there's more information that you need.

**Comment by nasrat-v** [comment]
I'm also on an arch-based distro, I fixed the issue by reinstalling the package from the AUR instead of using the python installer `pip`
If you cannot uninstall the previous package, you should overwrite it.

For example with the package manager `yay`:
```SH
yay undervolt --overwrite "/usr/bin/undervolt"
```
