### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'modprobe'

### ISSUE THREAD

**Issue by firebitsbr** [georgewhewell/undervolt#183]
$ undervolt --temp 80
Traceback (most recent call last):
  File "/home/test/anaconda3/bin/undervolt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/test/anaconda3/lib/python3.11/site-packages/undervolt.py", line 398, in main
    subprocess.check_call(['modprobe', 'msr'])
  File "/home/test/anaconda3/lib/python3.11/subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/anaconda3/lib/python3.11/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/anaconda3/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/test/anaconda3/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'modprobe'

**Comment by GermanAizek** [comment]
Same error on Debian 12 Linux kernel 6.10
