### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted using sudo undervolt

### ISSUE THREAD

**Issue by Alex2610** [georgewhewell/undervolt#184]
Hi, when trying to run undervolt I get:

```
$ sudo undervolt -r
temperature target: -2 (98C)
Traceback (most recent call last):
  File "/usr/local/bin/undervolt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/undervolt.py", line 457, in main
    voltage = read_offset(plane, msr)
  File "/usr/local/lib/python3.10/dist-packages/undervolt.py", line 209, in read_offset
    write_msr(value_to_write, msr.addr_voltage_offsets)
  File "/usr/local/lib/python3.10/dist-packages/undervolt.py", line 82, in write_msr
    os.write(f, pack('Q', val))
PermissionError: [Errno 1] Operation not permitted
```
SPECS:
_INTEL I5-I8250U ACER ASPIRE A315-53G-551Y_

**Comment by Alex2610** [comment]
SOLVED: Secure boot not disabled, had to put a "supervisor password" on BIOS, disable secureboot and then remove the password...

ADD ACER ASPIRE A315-53G-551Y on supported devices!!
