### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted when sudo undervolt --read

### ISSUE THREAD

**Issue by danielelongo14** [georgewhewell/undervolt#191]
Hello, i got this error with Ubuntu 22.03 when executing the command:
temperature target: -5 (95C)
Traceback (most recent call last):
  File "/usr/local/bin/undervolt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/undervolt.py", line 457, in main
    voltage = read_offset(plane, msr)
  File "/usr/local/lib/python3.10/dist-packages/undervolt.py", line 209, in read_offset
    write_msr(value_to_write, msr.addr_voltage_offsets)
  File "/usr/local/lib/python3.10/dist-packages/undervolt.py", line 82, in write_msr
    os.write(f, pack('Q', val))
PermissionError: [Errno 1] Operation not permitted

**Comment by p0ll3** [comment]
did you find a fix for this issue?

**Comment by danielelongo14** [comment]
No I'm not using Ubuntu anymore at the moment

**Comment by JosefSchoenberger** [comment]
This most likely comes from the Lockdown LSM, which prevents direct access on MSRs from userspace. Lockdown is automatically enabled with secure boot, which in turn is enabled by default on Ubuntu.

**Comment by SeniorMatt** [comment]
I managed to do that using this
`sudo pipx run undervolt --read`
