### ISSUE TITLE
Intel i7-5500U reports large offsets for all except core

### ISSUE THREAD

**Issue by andrewrabert** [georgewhewell/undervolt#9]
After a fresh boot, I'm seeing large offsets for everything except **core**.
```
$ sudo undervolt -v -r
INFO:root:Writing 0x8000001000000000 to /dev/cpu/3/msr
INFO:root:Writing 0x8000001000000000 to /dev/cpu/2/msr
INFO:root:Writing 0x8000001000000000 to /dev/cpu/1/msr
INFO:root:Writing 0x8000001000000000 to /dev/cpu/0/msr
INFO:root:Read 0x0 from /dev/cpu/0/msr
core: 0.0 mV
INFO:root:Writing 0x8000011000000000 to /dev/cpu/3/msr
INFO:root:Writing 0x8000011000000000 to /dev/cpu/2/msr
INFO:root:Writing 0x8000011000000000 to /dev/cpu/1/msr
INFO:root:Writing 0x8000011000000000 to /dev/cpu/0/msr
INFO:root:Read 0x10000000000 from /dev/cpu/0/msr
gpu: 510000.0 mV
INFO:root:Writing 0x8000021000000000 to /dev/cpu/3/msr
INFO:root:Writing 0x8000021000000000 to /dev/cpu/2/msr
INFO:root:Writing 0x8000021000000000 to /dev/cpu/1/msr
INFO:root:Writing 0x8000021000000000 to /dev/cpu/0/msr
INFO:root:Read 0x20000000000 from /dev/cpu/0/msr
cache: 1022000.0 mV
INFO:root:Writing 0x8000031000000000 to /dev/cpu/3/msr
INFO:root:Writing 0x8000031000000000 to /dev/cpu/2/msr
INFO:root:Writing 0x8000031000000000 to /dev/cpu/1/msr
INFO:root:Writing 0x8000031000000000 to /dev/cpu/0/msr
INFO:root:Read 0x30000000000 from /dev/cpu/0/msr
uncore: 1534000.0 mV
INFO:root:Writing 0x8000041000000000 to /dev/cpu/3/msr
INFO:root:Writing 0x8000041000000000 to /dev/cpu/2/msr
INFO:root:Writing 0x8000041000000000 to /dev/cpu/1/msr
INFO:root:Writing 0x8000041000000000 to /dev/cpu/0/msr
INFO:root:Read 0x40000000000 from /dev/cpu/0/msr
analogio: 2046000.0 mV
```
Using [linux-intel-undervolt-tool](https://github.com/hedgepigdaniel/linux-intel-undervolt-tool/), I see everything set to 0.
```
$ sudo intel-undervolt read
CPU (0): -0.00 mV
GPU (1): -0.00 mV
CPU Cache (2): -0.00 mV
System Agent (3): -0.00 mV
Analog I/O (4): -0.00 mV
```

Undervolting the **core** to -100 works as expected.
```
$ sudo undervolt -v --core -100
INFO:root:Setting core offset to -100mV
INFO:root:Writing 0x80000011f3400000 to /dev/cpu/3/msr
INFO:root:Writing 0x80000011f3400000 to /dev/cpu/2/msr
INFO:root:Writing 0x80000011f3400000 to /dev/cpu/1/msr
INFO:root:Writing 0x80000011f3400000 to /dev/cpu/0/msr
INFO:root:Writing 0x8000001000000000 to /dev/cpu/3/msr
INFO:root:Writing 0x8000001000000000 to /dev/cpu/2/msr
INFO:root:Writing 0x8000001000000000 to /dev/cpu/1/msr
INFO:root:Writing 0x8000001000000000 to /dev/cpu/0/msr
INFO:root:Read 0xf3400000 from /dev/cpu/0/msr

$ sudo undervolt -v -r
INFO:root:Writing 0x8000001000000000 to /dev/cpu/3/msr
INFO:root:Writing 0x8000001000000000 to /dev/cpu/2/msr
INFO:root:Writing 0x8000001000000000 to /dev/cpu/1/msr
INFO:root:Writing 0x8000001000000000 to /dev/cpu/0/msr
INFO:root:Read 0xf3400000 from /dev/cpu/0/msr
core: -99.61 mV
INFO:root:Writing 0x8000011000000000 to /dev/cpu/3/msr
INFO:root:Writing 0x8000011000000000 to /dev/cpu/2/msr
INFO:root:Writing 0x8000011000000000 to /dev/cpu/1/msr
INFO:root:Writing 0x8000011000000000 to /dev/cpu/0/msr
INFO:root:Read 0x10000000000 from /dev/cpu/0/msr
gpu: 510000.0 mV
INFO:root:Writing 0x8000021000000000 to /dev/cpu/3/msr
INFO:root:Writing 0x8000021000000000 to /dev/cpu/2/msr
INFO:root:Writing 0x8000021000000000 to /dev/cpu/1/msr
INFO:root:Writing 0x8000021000000000 to /dev/cpu/0/msr
INFO:root:Read 0x20000000000 from /dev/cpu/0/msr
cache: 1022000.0 mV
INFO:root:Writing 0x8000031000000000 to /dev/cpu/3/msr
INFO:root:Writing 0x8000031000000000 to /dev/cpu/2/msr
INFO:root:Writing 0x8000031000000000 to /dev/cpu/1/msr
INFO:root:Writing 0x8000031000000000 to /dev/cpu/0/msr
INFO:root:Read 0x30000000000 from /dev/cpu/0/msr
uncore: 1534000.0 mV
INFO:root:Writing 0x8000041000000000 to /dev/cpu/3/msr
INFO:root:Writing 0x8000041000000000 to /dev/cpu/2/msr
INFO:root:Writing 0x8000041000000000 to /dev/cpu/1/msr
INFO:root:Writing 0x8000041000000000 to /dev/cpu/0/msr
INFO:root:Read 0x40000000000 from /dev/cpu/0/msr
analogio: 2046000.0 mV

$ sudo intel-undervolt read 
CPU (0): -99.61 mV
GPU (1): -0.00 mV
CPU Cache (2): -0.00 mV
System Agent (3): -0.00 mV
Analog I/O (4): -0.00 mV
```

Undervolting the **gpu** to -100 seems to work, but fails to report correctly.
```
$ sudo undervolt -v --gpu -100
INFO:root:Setting gpu offset to -100mV
INFO:root:Writing 0x80000111f3400000 to /dev/cpu/3/msr
INFO:root:Writing 0x80000111f3400000 to /dev/cpu/2/msr
INFO:root:Writing 0x80000111f3400000 to /dev/cpu/1/msr
INFO:root:Writing 0x80000111f3400000 to /dev/cpu/0/msr
INFO:root:Writing 0x8000011000000000 to /dev/cpu/3/msr
INFO:root:Writing 0x8000011000000000 to /dev/cpu/2/msr
INFO:root:Writing 0x8000011000000000 to /dev/cpu/1/msr
INFO:root:Writing 0x8000011000000000 to /dev/cpu/0/msr
INFO:root:Read 0x100f3400000 from /dev/cpu/0/msr
Traceback (most recent call last):
  File "/home/draje/env/bin/undervolt", line 11, in <module>
    sys.exit(main())
  File "/home/draje/env/lib/python3.6/site-packages/undervolt.py", line 208, in main
    set_offset(plane, offset)
  File "/home/draje/env/lib/python3.6/site-packages/undervolt.py", line 168, in set_offset
    p=plane, t=target, r=format(read, '08x')))
ValueError: Unknown format code 'x' for object of type 'str'

$ sudo undervolt -v -r
INFO:root:Writing 0x8000001000000000 to /dev/cpu/3/msr
INFO:root:Writing 0x8000001000000000 to /dev/cpu/2/msr
INFO:root:Writing 0x8000001000000000 to /dev/cpu/1/msr
INFO:root:Writing 0x8000001000000000 to /dev/cpu/0/msr
INFO:root:Read 0xf3400000 from /dev/cpu/0/msr
core: -99.61 mV
INFO:root:Writing 0x8000011000000000 to /dev/cpu/3/msr
INFO:root:Writing 0x8000011000000000 to /dev/cpu/2/msr
INFO:root:Writing 0x8000011000000000 to /dev/cpu/1/msr
INFO:root:Writing 0x8000011000000000 to /dev/cpu/0/msr
INFO:root:Read 0x100f3400000 from /dev/cpu/0/msr
gpu: 511900.39 mV
INFO:root:Writing 0x8000021000000000 to /dev/cpu/3/msr
INFO:root:Writing 0x8000021000000000 to /dev/cpu/2/msr
INFO:root:Writing 0x8000021000000000 to /dev/cpu/1/msr
INFO:root:Writing 0x8000021000000000 to /dev/cpu/0/msr
INFO:root:Read 0x20000000000 from /dev/cpu/0/msr
cache: 1022000.0 mV
INFO:root:Writing 0x8000031000000000 to /dev/cpu/3/msr
INFO:root:Writing 0x8000031000000000 to /dev/cpu/2/msr
INFO:root:Writing 0x8000031000000000 to /dev/cpu/1/msr
INFO:root:Writing 0x8000031000000000 to /dev/cpu/0/msr
INFO:root:Read 0x30000000000 from /dev/cpu/0/msr
uncore: 1534000.0 mV
INFO:root:Writing 0x8000041000000000 to /dev/cpu/3/msr
INFO:root:Writing 0x8000041000000000 to /dev/cpu/2/msr
INFO:root:Writing 0x8000041000000000 to /dev/cpu/1/msr
INFO:root:Writing 0x8000041000000000 to /dev/cpu/0/msr
INFO:root:Read 0x40000000000 from /dev/cpu/0/msr
analogio: 2046000.0 mV

$ sudo intel-undervolt read
CPU (0): -99.61 mV
GPU (1): -99.61 mV
CPU Cache (2): -0.00 mV
System Agent (3): -0.00 mV
Analog I/O (4): -0.00 mV
```

**CPU**: Intel i7-5500U
**Machine**: XPS 13 9343
**OS**: Arch Linux
**Python**: Python 3.6.5
**Undervolt**: 0.2.3

**Comment by georgewhewell** [comment]
Thanks for the report- looks like we're unpacking the response incorrectly when plane != 0. I have a Broadwell machine at home, will check if I can replicate.

**Comment by georgewhewell** [comment]
@nvllsvm Could you test branch `bug/i5500u-response` please? It looks like on older models the plane prefix is included in the response and wasn't being discarded. Have tested on i4250u and seems to work.

**Comment by andrewrabert** [comment]
Confirmed working - thanks!

**Comment by andrewrabert** [comment]
As an aside - you might want to update the README to include the XPS 13 (9343) as confrimed working. :)
